package com.example.ivan.supermercado.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.ivan.supermercado.dao.Producto;
import com.example.ivan.supermercado.dao.Venta;

import com.example.ivan.supermercado.dao.ProductoDao;
import com.example.ivan.supermercado.dao.VentaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig productoDaoConfig;
    private final DaoConfig ventaDaoConfig;

    private final ProductoDao productoDao;
    private final VentaDao ventaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        productoDaoConfig = daoConfigMap.get(ProductoDao.class).clone();
        productoDaoConfig.initIdentityScope(type);

        ventaDaoConfig = daoConfigMap.get(VentaDao.class).clone();
        ventaDaoConfig.initIdentityScope(type);

        productoDao = new ProductoDao(productoDaoConfig, this);
        ventaDao = new VentaDao(ventaDaoConfig, this);

        registerDao(Producto.class, productoDao);
        registerDao(Venta.class, ventaDao);
    }
    
    public void clear() {
        productoDaoConfig.getIdentityScope().clear();
        ventaDaoConfig.getIdentityScope().clear();
    }

    public ProductoDao getProductoDao() {
        return productoDao;
    }

    public VentaDao getVentaDao() {
        return ventaDao;
    }

}
