package com.example.ivan.supermercado.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table VENTA.
 */
public class Venta {

    private Long id;
    /** Not-null value. */
    private java.util.Date fecha_venta;
    private int id_producto;
    private int cantidad;
    private float monto_total;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Venta() {
    }

    public Venta(Long id) {
        this.id = id;
    }

    public Venta(Long id, java.util.Date fecha_venta, int id_producto, int cantidad, float monto_total) {
        this.id = id;
        this.fecha_venta = fecha_venta;
        this.id_producto = id_producto;
        this.cantidad = cantidad;
        this.monto_total = monto_total;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public java.util.Date getFecha_venta() {
        return fecha_venta;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFecha_venta(java.util.Date fecha_venta) {
        this.fecha_venta = fecha_venta;
    }

    public int getId_producto() {
        return id_producto;
    }

    public void setId_producto(int id_producto) {
        this.id_producto = id_producto;
    }

    public int getCantidad() {
        return cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    public float getMonto_total() {
        return monto_total;
    }

    public void setMonto_total(float monto_total) {
        this.monto_total = monto_total;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
